{% set name = "PlasmidFinder" %}
{% set version = "3.0.3" %}
{% set sha256 = "da7474d1cebd3b69935baa0b388282e7b94f2302074034b785d34d2e34199fe1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/plasmidfinder/plasmidfinder-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - python >=3.10
    - pip
    - pdm-backend
    - kma
    - wget
    - tar
  run:
    - python >=3.10
    - biopython
    - pandas
    - tabulate
    - cgecore
    - blast
    - kma

test:
  imports:
    - plasmidfinder

about:
  home: "https://bitbucket.org/genomicepidemiology/plasmidfinder"
  license: "Apache-2.0"
  license_family: APACHE
  license_file: LICENSE
  summary: "PlasmidFinder allows identification of plasmids in total or partial sequenced isolates of bacteria."
  dev_url: "https://bitbucket.org/genomicepidemiology/plasmidfinder"
  doc_url: "https://bitbucket.org/genomicepidemiology/plasmidfinder/src/{{ version }}/README.md"

extra:
  identifiers:
    - doi:10.1128/AAC.02412-14
    - biotools:PlasmidFinder
    - usegalaxy-eu:plasmidfinder
  recipe-maintainers:
    - npavlovikj
